services:
  app:
    image: openjdk:21-jdk  # Use the OpenJDK 21 base image
    container_name: spring-demo
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    working_dir: /app  # Set the working directory to /app
    command: ["./mvnw", "spring-boot:run"]  # Run the Spring Boot application in development mode
    # entrypoint: ["./spring-entrypoint.sh"]
    ports:
      - "8080:8080"
    restart: always

  db:
    image: postgres:14
    container_name: spring_pgdb
    environment:
      POSTGRES_USER: ayushSpringUser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data 

volumes:
  dbdata:

